stages:
  - build
  - test
  - wacc-test-valid
  - wacc-test-invalid-semantic
  - wacc-test-invalid-syntax

make:
  stage: build
  artifacts: 
    untracked: true
  script:
    - make

main-test:
  stage: test
  script:
    - mvn test -Dtest=MainTest


.invalid/semanticErr/exit:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/semanticErr/exit/*.wacc"

.invalid/semanticErr/expressions:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/semanticErr/expressions/*.wacc"

.invalid/semanticErr/function:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/semanticErr/function/*.wacc"

.invalid/semanticErr/if:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/semanticErr/if/*.wacc"

.invalid/semanticErr/IO:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/semanticErr/IO/*.wacc"

.invalid/semanticErr/multiple:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/semanticErr/multiple/*.wacc"

.invalid/semanticErr/pairs:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/semanticErr/pairs/*.wacc"

.invalid/semanticErr/print:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/semanticErr/print/*.wacc"

.invalid/semanticErr/read:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/semanticErr/read/*.wacc"

.invalid/semanticErr/scope:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/semanticErr/scope/*.wacc"

.invalid/semanticErr/variables:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/semanticErr/variables/*.wacc"

.invalid/semanticErr/while:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/semanticErr/while/*.wacc"

.invalid/syntaxErr/array:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/syntaxErr/array/*.wacc"

.invalid/syntaxErr/basic:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/syntaxErr/basic/*.wacc"

.invalid/syntaxErr/expressions:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/syntaxErr/expressions/*.wacc"

.invalid/syntaxErr/function:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/syntaxErr/function/*.wacc"

.invalid/syntaxErr/if:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/syntaxErr/if/*.wacc"

.invalid/syntaxErr/pairs:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/syntaxErr/pairs/*.wacc"

.invalid/syntaxErr/print:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/syntaxErr/print/*.wacc"

.invalid/syntaxErr/sequence:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/syntaxErr/sequence/*.wacc"

.invalid/syntaxErr/variables:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/syntaxErr/variables/*.wacc"

.invalid/syntaxErr/while:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/invalid/syntaxErr/while/*.wacc"

.valid/advanced:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/advanced/*.wacc"

.valid/array:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/array/*.wacc"

valid/basic/exit:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd wacc_test
    - ./testDir.sh "sample_programs/valid/basic/exit/*.wacc"

.valid/basic/skip:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/basic/skip/*.wacc"

.valid/expressions:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/expressions/*.wacc"

.valid/function/nested_functions:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/function/nested_functions/*.wacc"

.valid/function/simple_functions:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/function/simple_functions/*.wacc"

.valid/if:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/if/*.wacc"

.valid/IO/print:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/IO/print/*.wacc"

.valid/IO/read:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/IO/read/*.wacc"

.valid/pairs:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/pairs/*.wacc"

.valid/runtimeErr/arrayOutOfBounds:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/runtimeErr/arrayOutOfBounds/*.wacc"

.valid/runtimeErr/divideByZero:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/runtimeErr/divideByZero/*.wacc"

.valid/runtimeErr/integerOverflow:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/runtimeErr/ integerOverflow/*.wacc"

.valid/runtimeErr/nullDereference:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/runtimeErr/nullDereference/*.wacc"

.valid/scope:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/scope/*.wacc"

.valid/sequence:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/sequence/*.wacc"

.valid/variables:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/variables/*.wacc"

.valid/while:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/valid/while/*.wacc"
