stages:
  - build
  - test
  - front-end
  - back-end
  - all-tests

clean:
  stage: build
  artifacts:
    untracked: true
  script:
    - make clean

make:
  stage: build
  artifacts:
    untracked: true
  script:
    - make

main-test:
  stage: test
  script:
    - mvn test


########## FRONT END TESTS ##########

symbol-table-test:
  stage: test
  script:
    - mvn test -Dtest=ParentRefSymbolTableTest

.front-end-tests:
  stage: front-end
  script:
    - cd wacc_test
    - ./testAll.sh

########## BACK END TESTS ##########

.valid/advanced:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/advanced/*.wacc"

.valid/array:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/array/*.wacc"

valid/basic/exit:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/basic/exit/*.wacc"

valid/basic/skip:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/basic/skip/*.wacc"

.valid/expressions:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/expressions/*.wacc"

.valid/function/nested_functions:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/function/nested_functions/*.wacc"

.valid/function/simple_functions:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/function/simple_functions/*.wacc"

.valid/if:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/if/*.wacc"

.valid/IO/print:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/IO/print/*.wacc"

.valid/IO/read:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/IO/read/*.wacc"

.valid/pairs:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/pairs/*.wacc"

.valid/runtimeErr/arrayOutOfBounds:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/runtimeErr/arrayOutOfBounds/*.wacc"

.valid/runtimeErr/divideByZero:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/runtimeErr/divideByZero/*.wacc"

.valid/runtimeErr/integerOverflow:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/runtimeErr/integerOverflow/*.wacc"

.valid/runtimeErr/nullDereference:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/runtimeErr/nullDereference/*.wacc"

.valid/scope:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/scope/*.wacc"

valid/sequence:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/sequence/*.wacc"

valid/variables:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/variables/*.wacc"

.valid/while:
  stage: back-end
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputDir.sh "sample_programs/valid/while/*.wacc"

########## ALL TESTS ##########

.scalable_tests:
  stage: all-tests
  interruptible: true
  script:
    - cd wacc_test
    - ./testOutputAll.sh
