stages:
  - build
  - test
  - wacc-test-valid
  - wacc-test-invalid-semantic
  - wacc-test-invalid-syntax

make:
  stage: build
  script:
    - make

main-test:
  stage: test
  script:
    - mvn test -Dtest=MainTest

foobar-test:
  stage: test
  script:
    - mvn test -Dtest=FoobarTest

.in.valid/semanticErr/exit:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/semanticErr/exit/*.wacc"

.in.valid/semanticErr/expressions:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/semanticErr/expressions/*.wacc"

.in.valid/semanticErr/function:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/semanticErr/function/*.wacc"

.in.valid/semanticErr/if:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/semanticErr/if/*.wacc"

.in.valid/semanticErr/IO:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/semanticErr/IO/*.wacc"

.in.valid/semanticErr/multiple:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/semanticErr/multiple/*.wacc"

.in.valid/semanticErr/pairs:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/semanticErr/pairs/*.wacc"

.in.valid/semanticErr/print:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/semanticErr/print/*.wacc"

.in.valid/semanticErr/read:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/semanticErr/read/*.wacc"

.in.valid/semanticErr/scope:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/semanticErr/scope/*.wacc"

.in.valid/semanticErr/variables:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/semanticErr/variables/*.wacc"

.in.valid/semanticErr/while:
  stage: wacc-test-invalid-semantic
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/semanticErr/while/*.wacc"

.in.valid/syntaxErr/array:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/syntaxErr/array/*.wacc"

.in.valid/syntaxErr/basic:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/syntaxErr/basic/*.wacc"

.in.valid/syntaxErr/expressions:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/syntaxErr/expressions/*.wacc"

.in.valid/syntaxErr/function:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/syntaxErr/function/*.wacc"

.in.valid/syntaxErr/if:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/syntaxErr/if/*.wacc"

.in.valid/syntaxErr/pairs:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/syntaxErr/pairs/*.wacc"

.in.valid/syntaxErr/print:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/syntaxErr/print/*.wacc"

.in.valid/syntaxErr/sequence:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/syntaxErr/sequence/*.wacc"

.in.valid/syntaxErr/variables:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/syntaxErr/variables/*.wacc"

.in.valid/syntaxErr/while:
  stage: wacc-test-invalid-syntax
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.in.valid/syntaxErr/while/*.wacc"

.valid/advanced:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/advanced/*.wacc"

.valid/array:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/array/*.wacc"

.valid/basic/exit:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/basic/exit/*.wacc"

.valid/basic/skip:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/basic/skip/*.wacc"

.valid/expressions:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/expressions/*.wacc"

.valid/function/nested_functions:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/function/nested_functions/*.wacc"

.valid/function/simple_functions:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/function/simple_functions/*.wacc"

.valid/if:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/if/*.wacc"

.valid/IO/print:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/IO/print/*.wacc"

.valid/IO/read:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/IO/read/*.wacc"

.valid/pairs:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/pairs/*.wacc"

.valid/runtimeErr/arrayOutOfBounds:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/runtimeErr/arrayOutOfBounds/*.wacc"

.valid/runtimeErr/divideByZero:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/runtimeErr/divideByZero/*.wacc"

.valid/runtimeErr/integerOverflow:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/runtimeErr/ integerOverflow/*.wacc"

.valid/runtimeErr/nullDereference:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/runtimeErr/nullDereference/*.wacc"

.valid/scope:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/scope/*.wacc"

.valid/sequence:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/sequence/*.wacc"

.valid/variables:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/variables/*.wacc"

.valid/while:
  stage: wacc-test-valid
  interruptible: true
  script:
    - cd test
    - ./testDir.sh "example_wacc/.valid/while/*.wacc"
