#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

system("mvn exec:java -Dexec.args=#{ARGV[0]}")
exit $?.exitstatus